// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID        int32
	UserID    pgtype.Int4
	FirstName pgtype.Text
	LastName  pgtype.Text
	Address   pgtype.Text
}

type User struct {
	ID                int32
	Email             pgtype.Text
	Password          pgtype.Text
	PhoneNumber       pgtype.Text
	Otp               pgtype.Text
	OtpExpirationTime pgtype.Timestamp
}
